### ISSUE TITLE
Issue after upgrading 

### ISSUE THREAD

**Issue by fiorthnir** [oxen-io/loki-core#1394]
Hello, 
I have a problem  after  upgrading my node to the version Salty Saga 8.1.5. 
So the upgrade went well and the command "oxend status" show that I am in the correct version. 
I cannot launch any loki related services or oxen related services. (well, for loki it should be normal, I think)

systemctl  status oxen-node
systemctl status oxen-storage-server
systemctl status lokinet-router
show me all errors. 
They cannot start. 

And on journalctl I have this one : "Error starting server: Failed to bind IPv4 (set to required)"

Thank you in advance.

**Comment by darcys22** [comment]
Hi Fiorth,

Thanks for reaching out. Is there anything else already bound to the port that oxend is trying to connect to?

Possibly there is still a lokid systemd process still running.

if you call systemctl status on lokid-node does it show anything?

alternatively if you are on ubuntu you can run
`sudo ss -tunlp`

To show already opened ports and we are looking for something already open on the same port

**Comment by jagerman** [comment]
I *believe* this is the same user I helped resolve the issue with via private messages on Telegram.  It turned out it was a conflict between loki-launcher and oxen services.  @fiorthnir if I am mistaken then please by all means reopen.
